name: sos_alert_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    

  hardware_buttons: ^2.0.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  permission_handler: ^11.0.1
  volume_button: ^1.0.2
  flutter_background: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
